# Generated by Django 5.2 on 2025-05-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBudgetSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_budget', models.FloatField(default=100.0)),
            ],
            options={
                'verbose_name': 'Global Budget Setting',
                'verbose_name_plural': 'Global Budget Setting',
            },
        ),
        migrations.RemoveField(
            model_name='kid',
            name='user',
        ),
        migrations.AlterField(
            model_name='income',
            name='kid',
            field=models.CharField(choices=[('shaina', 'Shaina'), ('viana', 'Viana')], max_length=10),
        ),
        migrations.AlterField(
            model_name='goal',
            name='kid',
            field=models.CharField(choices=[('shaina', 'Shaina'), ('viana', 'Viana')], max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='kid',
            field=models.CharField(choices=[('shaina', 'Shaina'), ('viana', 'Viana')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usedcredit',
            name='kid',
            field=models.CharField(choices=[('shaina', 'Shaina'), ('viana', 'Viana')], max_length=10),
        ),
        migrations.DeleteModel(
            name='MonthlyBudget',
        ),
        migrations.DeleteModel(
            name='Kid',
        ),
    ]
