# Generated by Django 5.2 on 2025-05-05 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_globalbudgetsetting_remove_kid_user_alter_income_kid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedcredit',
            name='title',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='globalbudgetsetting',
            name='monthly_budget',
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='income',
            name='title',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
